# Generated by Django 4.2.1 on 2023-05-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("x_disk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file",
            field=models.FileField(null=True, upload_to="documents/"),
        ),
    ]
