# Generated by Django 4.2.1 on 2023-05-06 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("x_disk", "0002_file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="size",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(524288),
                    django.core.validators.MinValueValidator(1),
                ]
            ),
        ),
    ]
